inherit_from: .rubocop.base.yml

AllCops:
  Include:
    - "lib/**/*.rb"
    - "spec/**/*.rb"
    - "bin/*"
    - "Rakefile"
    - "Gemfile"
    - "*.gemspec"
  Exclude:
    - "bin/ci-local"
    - "apps/admin/**/*"
    - "coverage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

RSpec/VerifiedDoubleReference:
  Exclude:
    - "spec/application/event_timeline_processor_spec.rb"
    - "spec/application/simulate_internal_spec.rb"
    - "spec/projector/projection_store_spec.rb"
    - "spec/projector/read_model_replay_spec.rb"

RSpec/MessageSpies:
  Exclude:
    - "spec/application/event_timeline_processor_spec.rb"
    - "spec/application/runner_internal_spec.rb"
    - "spec/application/simulate_internal_spec.rb"
    - "spec/projector/projection_store_spec.rb"
    - "spec/projector/read_model_replay_spec.rb"

RSpec/StubbedMock:
  Exclude:
    - "spec/application/event_timeline_processor_spec.rb"
    - "spec/application/runner_internal_spec.rb"
    - "spec/application/simulate_internal_spec.rb"

Performance/CollectionLiteralInLoop:
  Exclude:
    - "spec/benchmarking/input_generator_spec.rb"
