inherit_from: .rubocop.base.yml

AllCops:
  Include:
    - "lib/**/*.rb"
    - "spec/**/*.rb"
    - "bin/*"
    - "Rakefile"
    - "Gemfile"
    - "*.gemspec"
  Exclude:
    - "apps/admin/**/*"
    - "coverage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
