default: &default
  sources:
    - name: "BCRA"
      code: "BCRA"
      source_type: "api"
      version: "v1"
      active: true
      config:
        base_currency: "USD"
        quote_currency: "ARS"
        markets:
          - "USDARS"
          - "EURARS"
        market_currency_codes:
          USDARS: "USD"
          EURARS: "EUR"
        base_url: "https://api.bcra.gob.ar/estadisticascambiarias/v1.0"
        currency_code: "USD"

development: *default
test: *default
production: *default
