enforce_dependencies: true
enforce_privacy: true
public_path: app
dependencies:
  - "app/domains/core"
  - "app/domains/artifacts"
  - "app/domains/dashboard"
  - "app/domains/fx"
  - "app/domains/validation"
