name: Mutation Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *"
  push:
    branches:
      - main
      - development
    paths:
      - "lib/**/*.rb"
      - "spec/**/*.rb"

jobs:
  mutant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run mutation testing
        run: bundle exec mutant run --integration rspec --ignore-subject FCS::Engine::ValuationEngine --ignore-subject FCS::Engine::TradeSorter --ignore-subject FCS::Engine::LedgerState "FCS::Engine*"
